In [1]:
import numpy as np

In [ ]:
# shiftLeft
def shiftLeft(arr):
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0
  return arr

arr = np.array([1, 2, 3, 4, 5, 6])
print(shiftLeft(arr))

[2 3 4 5 6 0]


In [ ]:
#shiftRight
def shiftRight(arr):
  for i in range(len(arr)-1, 0, -1):
    arr[i] = arr[i-1]
  arr[0] = 0
  return arr

arr = np.array([1, 2, 3, 4, 5, 6])
print(shiftRight(arr))

[0 1 2 3 4 5]


In [ ]:
#rotateLeft
def rotateLeft(arr):
  temp = arr[0]
  arr = shiftLeft(arr)
  arr[len(arr)-1] = temp
  return arr

arr = np.array([1, 2, 3, 4, 5, 6])
print(rotateLeft(arr))

[2 3 4 5 6 1]


In [ ]:
#rotateRight
def rotateRight(arr):
  temp = arr[len(arr)-1]
  arr = shiftRight(arr)
  arr[0] = temp
  return arr

arr = np.array([1, 2, 3, 4, 5, 6])
print(rotateRight(arr))

[6 1 2 3 4 5]


In [ ]:
#reverse (out of place)
def reverse_OutofPlace(arr):
  arr1 = np.zeros(arr.shape, dtype="int")
  for i in range(len(arr)-1, -1, -1):
    arr1[len(arr)-1-i] = arr[i]
  return arr1

arr = np.array([1, 2, 3, 4, 5, 6])
print(reverse_OutofPlace(arr))

[6 5 4 3 2 1]


In [ ]:
#reverse (in-place)
def reverse_inPlace(arr):
  i = 0
  j = len(arr)-1
  while i<j:
    temp = arr[i]
    arr[i] = arr[j]
    arr[j] = temp

    i += 1
    j -= 1
  return arr

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(reverse_inPlace(arr))

[7 6 5 4 3 2 1]


In [ ]:
#resize
def resizeArray(oldArray, newCapacity):
  newArray = np.zeros(newCapacity, dtype="int")
  for i in range(len(oldArray)):
    newArray[i] = oldArray[i]
  return newArray

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(resizeArray(arr, len(arr)+1))

[1 2 3 4 5 6 7 0]


In [ ]:
#insert
def insert(arr, size, element, index):
  if size==len(arr):
    newArray = np.zeros(len(arr)+1, dtype="int")
    for i in range(len(arr)):
      newArray[i] = arr[i]
    arr = newArray

  if index == len(arr)-1:
      arr[index] = element
  else:
    for i in range(len(arr)-1, index, -1):
      arr[i] = arr[i-1]
    arr[index] = element
  size += 1
  return arr


arr = np.array([0, 0, 0, 1, 2, 3, 4, 5, 6, 0, 0, 0])
print(insert(arr, 6, 10, 5))

[ 0  0  0  1  2 10  3  4  5  6  0  0]


In [ ]:
#remove
def remove(arr, size, index):
  if index==size-1:
    arr[index] = 0
  else:
    for i in range(index+1, len(arr)):
      arr[i-1] = arr[i]
    arr[len(arr)-1] = 0
  return arr

arr = np.array([1, 2, 3, 4, 5, 6, 7, 0, 0])
print(remove(arr, 7, 2))

[1 2 4 5 6 7 0 0 0]


In [ ]:
#bubble sort
def bubbleSort(arr):
  for i in range(0, len(arr)-1):
    for j in range(1, len(arr)-i):
      if arr[j] < arr[j-1]:
        temp = arr[j]
        arr[j] = arr[j-1]
        arr[j-1] = temp
  return arr


arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(bubbleSort(arr))

[ 0  1  2  3  4  5  6  6  7  8  9 10]


In [ ]:
#selection sort
def selectionSort(arr):
  for i in range(0, len(arr)-1):
    min_index = i
    for j in range(i+1, len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    temp = arr[i]
    arr[i] = arr[min_index]
    arr[min_index] = temp
  return arr

arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(selectionSort(arr))

[ 0  1  2  3  4  5  6  6  7  8  9 10]


In [ ]:
#binary search
def binarySearch(arr, value):
  arr = selectionSort(arr)
  lo = 0
  hi = len(arr)-1
  while lo<=hi:
    mid = (lo+hi)//2
    if arr[mid]==value:
      return f"Value found at {mid}"
    elif arr[mid]>value:
      hi = mid-1
    elif arr[mid]<value:
      lo=mid+1
  return f"Value not found"

arr = np.array([2, 4, 6, 8, 9, 13, 15, 20])
print(binarySearch(arr, 20))

Value found at 7


In [ ]:
#multidimensional array
#iteration row-wise
def iteration(arr):
  row, col = arr.shape
  for i in range(row):
    for j in range(col):
      print(arr[i][j], end=" ")


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
iteration(arr)

1 2 3 4 5 6 7 8 9 

In [ ]:
#multidimensional array
#iteration col-wise
def iteration(arr):
  row, col = arr.shape
  for i in range(col):
    for j in range(row):
      print(arr[j][i], end=" ")


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
iteration(arr)

1 4 7 2 5 8 3 6 9 

In [ ]:
#Summation - along the rows and create the resultant array
def summation(arr):
  row, col = arr.shape
  result = np.zeros(shape=(row, 1), dtype="int")
  for i in range(row):
    sum = 0
    for j in range(col):
      sum += arr[i][j]
    result[i][0] = sum
  return result

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(summation(arr))

[[ 6]
 [15]
 [24]]


In [ ]:
#Summation - along the cols and create the resultant array
def summation(arr):
  row, col = arr.shape
  result = np.zeros(shape=(1, col), dtype="int")
  for i in range(row):
    sum = 0
    for j in range(col):
      sum += arr[j][i]
    result[0][i] = sum
  return result

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(summation(arr))

[[12 15 18]]


In [ ]:
#Find the largest number in a 2D array
def findLargestNumber(arr):
  max = arr[0][0]
  row, col = arr.shape
  for i in range(row):
    for j in range(col):
      if arr[i][j] >= max:
        max = arr[i][j]
  return max

arr = np.array([[-10, -2, -3], [-4, -23, -6], [-27, -18, -9]])
print(findLargestNumber(arr))

-2


In [ ]:
#Find The Largest Number in Each Row in a 2D  Array. Then Find The Smallest Among Them
def findLargestNumber(arr):
  row, col = arr.shape
  result = np.zeros(shape=(row, 1), dtype="int")
  for i in range(row):
    row_max = arr[i][0]
    for j in range(col):
      cur_num = arr[i][j]
      if cur_num > row_max:
        row_max = cur_num
    result[i][0] = row_max
    print(f"{row_max} is the maximum in row {i}th row")
  min = result[0][0]
  for i in range(1, col):
    if result[i][0] < min:
      min = result[i][0]
  return f"{min} is the minimum amongst the largest in each row"





arr = np.array([[-10, -2, -3], [4, 23, 6], [27, 18, 9]])
print(findLargestNumber(arr))

-2 is the maximum in row 0th row
23 is the maximum in row 1th row
27 is the maximum in row 2th row
-2 is the minimum amongst the largest in each row


In [ ]:
#Find The Smallest Number in Each Column in a  2D Array. Then Find The Largest Among Them

In [ ]:
def swapColumn(arr):
  row, col = arr.shape
  for i in range(row):
    for j in range(col//2):
      temp = arr[i][j]
      arr[i][j] = arr[i][col-1-j]
      arr[i][col-1-j] = temp
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(swapColumn(arr))

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
def swapRows(arr):
  row, col = arr.shape
  for i in range(col):
    for j in range(row//2):
      temp = arr[j][i]
      arr[j][i] = arr[row-1-j][i]
      arr[row-1-j][i] = temp
  return arr

arr = np.array([[1, 2, 3], [5, 6, 7]])
print(swapRows(arr))

[[5 6 7]
 [1 2 3]]


In [ ]:
#Add elements of a primary diagonal (square matrix)
def primary_diagonal(arr):
  row, col = arr.shape
  sum = 0
  for i in range(row):
    sum += arr[i][i]
  return sum

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(primary_diagonal(arr))


15


In [ ]:
#Add elements of a primary diagonal (general form or for a non square matrix)
def primary_diagonal(arr):
  row, col = arr.shape
  sum = 0
  for i in range(row):
    if i>=col:
      break
    else:
      sum += arr[i][i]
  return sum

arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print(primary_diagonal(arr))

15


In [ ]:
#row upshift
def row_upshift(arr):
  row, col = arr.shape
  for i in range(1, row):
    for j in range(col):
      arr[i-1][j] = arr[i][j]
  for i in range(col):
    arr[row-1][i] = 0
  return arr

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(row_upshift(arr))


[[4 5 6]
 [7 8 9]
 [0 0 0]]


In [ ]:
#column rightshift
def col_rightShift(arr):
  row, col = arr.shape
  for i in range(col-1, -1, -1):
    for j in range(row):
      arr[j][i] = arr[j][i-1]
  for i in range(row):
    arr[i][0] = 0
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(col_rightShift(arr))


[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 0  9 10 11]]


In [ ]:
#column leftShift
def col_leftShift(arr):
  row, col = arr.shape
  for i in range(1, col):
    for j in range(row):
      arr[j][i-1] = arr[j][i]
  for i in range(row):
    arr[i][col-1] = 0

  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(col_leftShift(arr))


[[ 2  3  4  0]
 [ 6  7  8  0]
 [10 11 12  0]]


In [ ]:
#row uprotate
def row_upRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(col, dtype="int")
  for i in range(col):
    temp_arr[i] = arr[0][i]
  for i in range(1, row):
    for j in range(col):
      arr[i-1][j] = arr[i][j]

  for i in range(col):
    arr[row-1][i] = temp_arr[i]

  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(row_upRotate(arr))


[[ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [ ]:
#row uprotate
def row_downRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(col, dtype="int")
  for i in range(col):
    temp_arr[i] = arr[row-1][i]
  for i in range(row-1, -1, -1):
    for j in range(col):
      arr[i][j] = arr[i-1][j]

  for i in range(col):
    arr[0][i] = temp_arr[i]

  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(row_downRotate(arr))


[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
def col_rightRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(row, dtype="int")
  for i in range(row):
    temp_arr[i] = arr[i][col-1]
  for i in range(col-1, -1, -1):
    for j in range(row):
      arr[j][i] = arr[j][i-1]

  for i in range(row):
    arr[i][0] = temp_arr[i]
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(col_rightRotate(arr))


[[ 4  1  2  3]
 [ 8  5  6  7]
 [12  9 10 11]]


In [ ]:
def col_leftRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(row, dtype="int")
  for i in range(row):
    temp_arr[i] = arr[i][0]

  for i in range(1, col):
    for j in range(row):
      arr[j][i-1] = arr[j][i]

  for i in range(row):
    arr[i][col-1] = temp_arr[i]
  return arr

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(col_leftRotate(arr))


[[2 3 1]
 [5 6 4]
 [8 9 7]]


In [8]:
class Node:
  def __init__(self, value, next):
    self.value = value
    self.next = next

class linkedList:
  def __init__(self, arr):
    self.head = Node(arr[0], None)
    tail = self.head
    for i in range(1, len(arr)):
      x = Node(arr[i], None)
      tail.next = x
      tail = x

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
obj = linkedList(arr)

1

In [21]:
def printNode(head):
  temp = head
  while temp != None:
    print(temp.value, end=" ")
    temp = temp.next

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
obj = linkedList(arr)
printNode(obj.head)

1 2 3 4 5 6 7 8 9 10 

In [13]:
def countNode(head):
  temp = head
  count = 0
  while temp != None:
    count += 1
    temp = temp.next
  return count

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
obj = linkedList(arr)
print(countNode(obj.head))

10


In [14]:
def getNode(head, index):
  count = 0
  temp = head
  while temp != None:
    if count == index:
      return temp
    else:
      temp = temp.next
      count += 1
  return f"Not a valid index"


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
print(getNode(obj.head, 0))
print(getNode(obj.head, 1))
print(getNode(obj.head, 2))
print(getNode(obj.head, -1))

Not a valid index


In [16]:
def getElement(head, index):
  temp = head
  count = 0
  while temp != None:
    if count == index:
      return temp.value
    else:
      temp = temp.next
      count += 1
  return f"Not a valid index"

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
print(getElement(obj.head, 0))
print(getElement(obj.head, 5))
print(getElement(obj.head, 9))
print(getElement(obj.head, -1))

10
60
Not a valid index
Not a valid index


In [17]:
def update(head, index, element):
  temp = head
  count = 0
  while temp != None:
    if count == index:
      temp.value = element
      break
    else:
      temp = temp.next
      count += 1

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
print(getElement(obj.head, 2))
update(obj.head, 2, 100)
print(getElement(obj.head, 2))

30
100


In [18]:
def search(head, element):
  temp = head
  count = 0
  while temp != None:
    if temp.value == element:
      return count
    else:
      temp = temp.next
      count += 1
  return f"The element is not found"

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
print(search(obj.head, 50))

4


In [24]:
def insert(head, index, element):
  total_nodes = countNode(head)

  if index == 0:                        #Inserting at the beginning
    n = Node(element, head)
    head = n

  elif index>0 and index<total_nodes:        #Inserting at the middle
    previous_node = getNode(head, index-1)
    next_node = getNode(head, index)
    n = Node(element, next_node)
    previous_node.next = n

  elif index==total_nodes:                     #Inserting at the end
    n = Node(element, None)
    previous_node = getNode(head, index-1)
    previous_node.next = n

  else:
    print(f"Index out of bound")

  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
head = insert(obj.head, 2, 100)

print(head)
printNode(head)

10 20 100 30 40 50 60 70 80 

In [26]:
def remove(head, index):
  total_nodes = countNode(head)

  if index == 0:
    head = head.next
  elif index>0 and index<total_nodes:
    previous_node = getNode(head, index-1)
    next_node = getNode(head, index)
    previous_node.next = next_node.next
  else:
    print("Invalid index")
  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
printNode(obj.head)
head = remove(obj.head, 3)
print()
printNode(head)


10 20 30 40 50 60 70 80 
10 20 30 50 60 70 80 

In [27]:
def rightRotate(head):
  total_nodes = countNode(head)
  last_node = getNode(head, total_nodes-1)
  second_last_node = getNode(head, total_nodes-2)
  last_node.next = head
  second_last_node.next = None
  head = last_node
  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
head = rightRotate(obj.head)
printNode(head)

80 10 20 30 40 50 60 70 

In [28]:
#Left rotate a linked list
def leftRotate(head):
  total_nodes = countNode(head)
  last_node = getNode(head, total_nodes-1)
  second_node = getNode(head, 1)
  last_node.next = head
  head.next = None
  head = second_node
  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
obj = linkedList(arr)
head = leftRotate(obj.head)
printNode(head)


20 30 40 50 60 70 80 10 