In [1]:
import numpy as np

In [2]:
class Node:
  def __init__(self, elem, weight=1, next=None):
    self.elem = elem
    self.weight = weight
    self.next = next


In [ ]:
class Undirected_Unweighted_Graph:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v):
    if self.adj[u] != None:
      temp = self.adj[u]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(v)
    else:
      self.adj[u] = Node(v)

    if self.adj[v] != None:
      temp = self.adj[v]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(u)
    else:
      self.adj[v] = Node(u)
  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

In [ ]:
class Undirected_Unweighted_Matrix:
  def __init__(self, n):
    self.num_of_vertex = n
    self.matrix = np.zeros(shape=(n, n), dtype="int")

  def addEdge(self, u, v):
    self.matrix[u-1][v-1] = 1
    self.matrix[v-1][u-1] = 1

  def show(self):
    print(self.matrix)

In [ ]:
class DirectedWeightedGraph:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v, w):
    if self.adj[u] != None:
      temp = self.adj[u]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(v, w)
    else:
      self.adj[u] = Node(v, w)

  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

In [ ]:
class DirectedWeightedMatrix:
  def __init__(self, n):
    self.num_of_vertex = n
    self.matrix = np.zeros(shape=(n, n), dtype="int")

  def addEdge(self, u, v, w):
    self.matrix[u-1][v-1] = w

  def show(self):
    print(self.matrix)

In [3]:
class UndirectedWeightedList:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v, w):
    if self.adj[u] == None:
      self.adj[u] = Node(v, w)
    else:
      head = self.adj[u]
      while head.next != None:
        head = head.next
      head.next = Node(v, w)

    if self.adj[v] == None:
      self.adj[v] = Node(u, w)
    else:
      head = self.adj[v]
      while head.next != None:
        head = head.next
      head.next = Node(u, w)

  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

G = UndirectedWeightedList(8)
G.addEdge(1, 2, 2)
G.addEdge(1, 8, 2)
G.addEdge(2, 3, 2)
G.addEdge(3, 6, 3)
G.addEdge(4, 3, 2)
G.addEdge(4, 8, 3)
G.addEdge(4, 5, 3)
G.addEdge(5, 6, 1)
G.addEdge(6, 2, 6)
G.addEdge(6, 1, 4)
G.addEdge(6, 7, 7)
G.addEdge(7, 3, 4)
G.addEdge(7, 4, 2)
G.addEdge(8, 7, 2)
G.addEdge(8, 5, 1)
G.addEdge(5, 1, 2)
G.addEdge(6, 8, 2)
G.show()

1: 2 --> 8 --> 6 --> 5 --> None
2: 1 --> 3 --> 6 --> None
3: 2 --> 6 --> 4 --> 7 --> None
4: 3 --> 8 --> 5 --> 7 --> None
5: 4 --> 6 --> 8 --> 1 --> None
6: 3 --> 5 --> 2 --> 1 --> 7 --> 8 --> None
7: 6 --> 3 --> 4 --> 8 --> None
8: 1 --> 4 --> 7 --> 5 --> 6 --> None


In [6]:
class UndirectedWeightedMatrix:
  def __init__(self, n):
    self.num_of_vertex = n
    self.matrix = np.zeros(shape=(n, n), dtype="int")

  def addEdge(self, u, v, w):
    self.matrix[u-1][v-1] = w
    self.matrix[v-1][u-1] = w

  def show(self):
    print(self.matrix)

G = UndirectedWeightedMatrix(8)
G.addEdge(1, 2, 2)
G.addEdge(1, 8, 2)
G.addEdge(2, 3, 2)
G.addEdge(3, 6, 3)
G.addEdge(4, 3, 2)
G.addEdge(4, 8, 3)
G.addEdge(4, 5, 3)
G.addEdge(5, 6, 1)
G.addEdge(6, 2, 6)
G.addEdge(6, 1, 4)
G.addEdge(6, 7, 7)
G.addEdge(7, 3, 4)
G.addEdge(7, 4, 2)
G.addEdge(8, 7, 2)
G.addEdge(8, 5, 1)
G.addEdge(5, 1, 2)
G.addEdge(6, 8, 2)
G.show()

[[0 2 0 0 2 4 0 2]
 [2 0 2 0 0 6 0 0]
 [0 2 0 2 0 3 4 0]
 [0 0 2 0 3 0 2 3]
 [2 0 0 3 0 1 0 1]
 [4 6 3 0 1 0 7 2]
 [0 0 4 2 0 7 0 2]
 [2 0 0 3 1 2 2 0]]
