In [ ]:
import numpy as np

## Linear Array

In [ ]:
# printing an array reversely
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
i = len(arr)-1
while i>=0:
  print(arr[i], end=" ")
  i -= 1

50 40 30 20 10 

In [ ]:
#Reversing an array
#This is an out of place approach because a new array has been created to store the array
def reverseArray(arr):
  arr1 = np.zeros(arr.shape, dtype="int")
  i = len(arr)-1
  j = 0
  while i>=0:
    arr1[j] = arr[i]
    i-=1
    j+=1
  return arr1

arr = np.array([10, 20, 30, 40, 50])
arr = reverseArray(arr)
print(arr)

[50 40 30 20 10]


In [ ]:
#Now this will be an in place approach where no new array will be created
def reverseArray(arr):
  x = len(arr)-1
  i = 0
  while i<len(arr)//2:
    temp = arr[i]
    arr[i] = arr[x-i]
    arr[x-i] = temp
    i += 1
  return arr

arr = np.array([10, 20, 30, 40, 50])
print(reverseArray(arr))


[50 40 30 20 10]


In [ ]:
#shiftRight --> right shifting an array by one place
def shiftRight(arr):
  i = len(arr)-1
  while i>=0:
    if i==0:
      arr[i] = 0
    else:
      arr[i] = arr[i-1]
    i-=1
  return arr


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(shiftRight(arr))


[ 0 10 20 30 40 50 60 70]


In [ ]:
#shiftLeft --> Left shifting an array by one place
def shiftLeft(arr):
  i = 0
  while i<len(arr):
    if i==len(arr)-1:
      arr[i] = 0
    else:
      arr[i] = arr[i+1]
    i+=1
  return arr


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(shiftLeft(arr))


[20 30 40 50 60 70 80  0]


In [ ]:
#RotateRight --> right rotate an array by one place
def rotateRight(arr):
  i = len(arr)-1
  temp = arr[i]
  while i>=0:
    if i==0:
      arr[i] = temp
    else:
      arr[i] = arr[i-1]
    i-=1
  return arr


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(rotateRight(arr))


[80 10 20 30 40 50 60 70]


In [ ]:
#RotateLeft --> left rotate an array by one place
def rotateLeft(arr):
  i = 0
  temp = arr[0]
  while i<len(arr):
    if i==len(arr)-1:
      arr[i] = temp
    else:
      arr[i] = arr[i+1]
    i+=1
  return arr


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(rotateLeft(arr))


[20 30 40 50 60 70 80 10]


In [ ]:
#LeftShift by k places
def leftShiftbyPlace(arr, place):
  i = 0
  while i<len(arr):
    if i+place>=len(arr):
      arr[i] = 0
    else:
      arr[i] = arr[i+place]
    i+=1
  return arr


arr = np.array([10, 20, 30, 40, 50, 60])
place = int(input())
print(leftShiftbyPlace(arr, place))

2
[30 40 50 60  0  0]


In [ ]:
#RightShift by k places
def rightShiftbyPlace(arr, place):
  i = len(arr)-1
  while i>=0:
    if i-place<0:
      arr[i] = 0
    else:
      arr[i] = arr[i-place]
    i-=1
  return arr


arr = np.array([10, 20, 30, 40, 50, 60])
place = int(input())
print(rightShiftbyPlace(arr, place))

3
[ 0  0  0 10 20 30]


In [ ]:
#rightRotate by k places
#I have to understand and do this again
def rotateRightbyPlace(arr, place):
  i = len(arr)-1
  temp_lst = []
  while i>=0:
    if i+place>=len(arr) and i>=place:
      temp_lst.append(arr[i])
      arr[i] = arr[i-place]
    elif i+place<len(arr) and i>=place:
      arr[i] = arr[i-place]
    else:
      arr[i] = temp_lst[i]
    i-=1
  return arr

arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(rotateRightbyPlace(arr, int(input())))

3
[70 60 50 10 20 30 40]


In [ ]:
#Remove an element by index
def removeAnElement(source, size, idx):
  for i in range(idx+1, len(source)):
    source[i-1] = source[i]
  source[len(source)-1] = 0
  return source


source = np.array([10, 20, 30, 40, 50, 0, 0])
print(removeAnElement(source, size=int(input()), idx=int(input())))

5
2
[10 20 40 50  0  0  0]


In [ ]:
#Remove all the occurance of an element from the array
def removeAllTheOccurance(source, size, element):
  temp = 0
  for i in range(len(source)):
    if source[i] == element:
      temp += 1
    else:
      source[i-temp] = source[i]
  for i in range(temp):
    source[len(source)-1-i] = 0
  return source


source = np.array([5, 3, 2, 5, 5, 6, 3, 5, 2, 1])
print(removeAllTheOccurance(source, int(input()), int(input())))

5
5
[3 2 6 3 2 1 0 0 0 0]


##Sorting Algorithgms

In [ ]:
#bubble sort
def bubbleSort(arr):
  for i in range(0, len(arr)-1):
    for j in range(1, len(arr)-i):
      if arr[j] < arr[j-1]:
        temp = arr[j]
        arr[j] = arr[j-1]
        arr[j-1] = temp
  return arr


arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(bubbleSort(arr))

[ 0  1  2  3  4  5  6  6  7  8  9 10]


In [ ]:
#selection sort
def selectionSort(arr):
  for i in range(0, len(arr)-1):
    min_index = i
    for j in range(i+1, len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    temp = arr[i]
    arr[i] = arr[min_index]
    arr[min_index] = temp
  return arr

arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(selectionSort(arr))

[ 0  1  2  3  4  5  6  6  7  8  9 10]


In [ ]:
#binary search
def binarySearch(arr, value):
  arr = selectionSort(arr)
  lo = 0
  hi = len(arr)-1
  while lo<=hi:
    mid = (lo+hi)//2
    if arr[mid]==value:
      return f"Value found at {mid}"
    elif arr[mid]>value:
      hi = mid-1
    elif arr[mid]<value:
      lo=mid+1
  return f"Value not found"

arr = np.array([2, 4, 6, 8, 9, 13, 15, 20])
print(binarySearch(arr, 20))

## Circular Array

In [ ]:
#Size --> How many elements are there
#Length --> How many elements it can held
#In circular array, first element can be any index
#Two variables are needed to be maintained 1. start 2. size

In [ ]:
#Traverse a simple circular array
arr = np.array([0, 0, 0, 0, 0, 10, 20, 30, 40, 50, 0])
start = 5
size = 5
index = start
for i in range(size):
  print(arr[index], end=" ")
  index += 1

10 20 30 40 50 

In [ ]:
#Traverse a circular array
arr = np.array([50, 60, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 20, 30, 40])
start = 12
size = 7
index = start
for i in range(size):
  if index<len(arr):
    print(arr[index], end=" ")
    index += 1
  else:
    index = 0
    print(arr[index], end=" ")
    index+=1

10 20 30 40 50 60 70 

In [ ]:
#Traverse a circular array
#This is the shortcut and general way
arr = np.array([50, 60, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 20, 30, 40])
start = 12
size = 7
index = start
for i in range(size):
  if index<len(arr):
    print(arr[index], end=" ")
    index = (index+1)%len(arr)

10 20 30 40 50 60 70 

In [ ]:
#Reverse printing a circular array
#Last Index == (start + size - 1) % len(arr)
arr = np.array([50, 60, 70, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 20, 30, 40])
start = 13
size = 8
last_index = (start+size-1) % len(arr)
for i in range(size):
  print(arr[last_index])
  last_index -= 1

80
70
60
50
40
30
20
10


In [ ]:
#Convert a linear array to a circular array
arr = np.array([10, 20, 30, 40, 50, 60, 0, 0, 0, 0, 0])
cir_arr = np.zeros(shape=arr.shape, dtype="int")

start = 8
size = 6
cur_index = start

for i in range(size):
  cir_arr[cur_index] = arr[i]
  cur_index = (cur_index+1)%len(arr)  #In this case, linear and circular array have the same length

print(cir_arr)


[40 50 60  0  0  0  0  0 10 20 30]


## Multi-dimensional Array

In [ ]:
#multidimensional array
#iteration row-wise
def iteration(arr):
  row, col = arr.shape
  for i in range(row):
    for j in range(col):
      print(arr[i][j], end=" ")


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
iteration(arr)

1 2 3 4 5 6 7 8 9 

In [ ]:
#multidimensional array
#iteration col-wise
def iteration(arr):
  row, col = arr.shape
  for i in range(col):
    for j in range(row):
      print(arr[j][i], end=" ")


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
iteration(arr)

1 4 7 2 5 8 3 6 9 

In [ ]:
#Summation - along the rows and create the resultant array
def summation(arr):
  row, col = arr.shape
  result = np.zeros(shape=(row, 1), dtype="int")
  for i in range(row):
    sum = 0
    for j in range(col):
      sum += arr[i][j]
    result[i][0] = sum
  return result

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(summation(arr))

[[ 6]
 [15]
 [24]]


In [ ]:
#Summation - along the cols and create the resultant array
def summation(arr):
  row, col = arr.shape
  result = np.zeros(shape=(1, col), dtype="int")
  for i in range(row):
    sum = 0
    for j in range(col):
      sum += arr[j][i]
    result[0][i] = sum
  return result

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(summation(arr))

[[12 15 18]]


In [ ]:
def swapColumn(arr):
  row, col = arr.shape
  for i in range(row):
    for j in range(col//2):
      temp = arr[i][j]
      arr[i][j] = arr[i][col-1-j]
      arr[i][col-1-j] = temp
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(swapColumn(arr))

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
def swapRows(arr):
  row, col = arr.shape
  for i in range(col):
    for j in range(row//2):
      temp = arr[j][i]
      arr[j][i] = arr[row-1-j][i]
      arr[row-1-j][i] = temp
  return arr

arr = np.array([[1, 2, 3], [5, 6, 7]])
print(swapRows(arr))

[[5 6 7]
 [1 2 3]]


In [ ]:
#Add elements of a primary diagonal (square matrix)
def primary_diagonal(arr):
  row, col = arr.shape
  sum = 0
  for i in range(row):
    sum += arr[i][i]
  return sum

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(primary_diagonal(arr))


15


In [ ]:
#Add elements of a primary diagonal (general form or for a non square matrix)
def primary_diagonal(arr):
  row, col = arr.shape
  sum = 0
  for i in range(row):
    if i>=col:
      break
    else:
      sum += arr[i][i]
  return sum

arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print(primary_diagonal(arr))

15


In [ ]:
#row upshift
def row_upshift(arr):
  row, col = arr.shape
  for i in range(1, row):
    for j in range(col):
      arr[i-1][j] = arr[i][j]
  for i in range(col):
    arr[row-1][i] = 0
  return arr

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(row_upshift(arr))


[[4 5 6]
 [7 8 9]
 [0 0 0]]


In [ ]:
#row downshift
def row_downshift(arr):
  row, col = arr.shape
  for i in range(row-1, -1, -1):
    for j in range(col):
      arr[i][j] = arr[i-1][j]

  for i in range(col):
    arr[0][i] = 0
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(row_downshift(arr))


[[0 0 0 0]
 [1 2 3 4]
 [5 6 7 8]]


In [ ]:
#column rightshift
def col_rightShift(arr):
  row, col = arr.shape
  for i in range(col-1, -1, -1):
    for j in range(row):
      arr[j][i] = arr[j][i-1]
  for i in range(row):
    arr[i][0] = 0
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(col_rightShift(arr))


[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 0  9 10 11]]


In [ ]:
#column leftShift
def col_leftShift(arr):
  row, col = arr.shape
  for i in range(1, col):
    for j in range(row):
      arr[j][i-1] = arr[j][i]
  for i in range(row):
    arr[i][col-1] = 0

  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(col_leftShift(arr))


[[ 2  3  4  0]
 [ 6  7  8  0]
 [10 11 12  0]]


In [ ]:
#row uprotate
def row_upRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(col, dtype="int")
  for i in range(col):
    temp_arr[i] = arr[0][i]
  for i in range(1, row):
    for j in range(col):
      arr[i-1][j] = arr[i][j]

  for i in range(col):
    arr[row-1][i] = temp_arr[i]

  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(row_upRotate(arr))

[[ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [ ]:
#row uprotate
def row_downRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(col, dtype="int")
  for i in range(col):
    temp_arr[i] = arr[row-1][i]
  for i in range(row-1, -1, -1):
    for j in range(col):
      arr[i][j] = arr[i-1][j]

  for i in range(col):
    arr[0][i] = temp_arr[i]

  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(row_downRotate(arr))

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
def col_rightRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(row, dtype="int")
  for i in range(row):
    temp_arr[i] = arr[i][col-1]
  for i in range(col-1, -1, -1):
    for j in range(row):
      arr[j][i] = arr[j][i-1]

  for i in range(row):
    arr[i][0] = temp_arr[i]
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(col_rightRotate(arr))


[[ 4  1  2  3]
 [ 8  5  6  7]
 [12  9 10 11]]


In [ ]:
def col_leftRotate(arr):
  row, col = arr.shape
  temp_arr = np.zeros(row, dtype="int")
  for i in range(row):
    temp_arr[i] = arr[i][0]

  for i in range(1, col):
    for j in range(row):
      arr[j][i-1] = arr[j][i]

  for i in range(row):
    arr[i][col-1] = temp_arr[i]
  return arr

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(col_leftRotate(arr))


[[2 3 1]
 [5 6 4]
 [8 9 7]]


In [ ]:
#add 2 matrices
def add_matrix(arr1, arr2):
  row, col = arr1.shape
  new_arr = np.zeros(shape=(row, col), dtype="int")
  for i in range(row):
    for j in range(col):
      new_arr[i][j] = arr1[i][j]+arr2[i][j]
  return new_arr

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[7, 8, 9], [4, 5, 6], [1, 2, 3]])
print(add_matrix(arr1, arr2))

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]


In [ ]:
def multiply_matrix(arr1, arr2):
  row1, col1 = arr1.shape
  row2, col2 = arr2.shape
  result = np.zeros(shape=(row1, col2), dtype="int")
  for i in range(row1):
    for j in range(col2):
      for k in range(col1):
        result[i][j] += arr1[i][k] * arr2[k][j]
  return result

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(multiply_matrix(arr1, arr2))

[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]
