In [ ]:
import numpy as np

In [ ]:
def shiftLeft(arr):
  i = 1
  while i<len(arr):
    arr[i-1] = arr[i]
    i += 1
  arr[len(arr)-1] = 0
  print(arr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
shiftLeft(arr)

[ 2  3  4  5  6  7  8  9 10  0]


In [ ]:
#selection sort
def selectionSort(arr):
  for i in range(len(arr)-1):
    min_index = i
    for j in range(i+1, len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    temp = arr[i]
    arr[i] = arr[min_index]
    arr[min_index] = temp
  return arr

arr = np.array([10, 2, 3, 7, 26, 5, 8, 6, 9, 11])
selectionSort(arr)

array([ 2,  3,  5,  6,  7,  8,  9, 10, 11, 26])

In [ ]:
# Bubble sort
def bubbleSort(arr):
  for i in range(0, len(arr)-1):
    for j in range(1, len(arr)-i):
      if arr[j] < arr[j-1]:
        temp = arr[j]
        arr[j] = arr[j-1]
        arr[j-1] = temp
  return arr


arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
bubbleSort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [ ]:
#Binary Search
def binarySearch(arr, value):
  arr = selectionSort(arr)
  low = 0
  high = len(arr)-1
  while low<=high:
    mid = (low+high)//2
    if arr[mid] == value:
      return f"Value found at index {mid}"
    elif arr[mid] < value:
      low = mid + 1
    elif arr[mid] > value:
      high = mid - 1
  return f"Value not found"


arr = np.array([10, 2, 3, 7, 26, 5, 8, 6, 9, 11])
print(binarySearch(arr, 3))

Value found at index 1


In [ ]:
#selection sort
def selectionSort(arr):
  for i in range(0, len(arr)):
    min_index = i
    for j in range(i+1, len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    temp = arr[i]
    arr[i] = arr[min_index]
    arr[min_index] = temp

  return arr

arr = np.array([10, 2, 3, 7, 26, 5, 8, 6, 9, 11])
print(selectionSort(arr))

[ 2  3  5  6  7  8  9 10 11 26]


In [ ]:
#bubble sort
def bubbleSort(arr):
  for i in range(0, len(arr)-1):
    for j in range(1, len(arr)-i):
      if arr[j] < arr[j-1]:
        temp = arr[j]
        arr[j] = arr[j-1]
        arr[j-1] = temp
  return arr

arr = np.array([10, 2, 3, 7, 26, 5, 8, 6, 9, 11])
print(bubbleSort(arr))

[ 2  3  5  6  7  8  9 10 11 26]


In [ ]:
cir_arr = np.array([0, 0, 0, 0, 0, 10, 20, 30, 40, 50, 0])
size = 5
start = 5
cur_index = start
for i in range(size):
  print(cir_arr[cur_index], end=" ")
  cur_index += 1

10 20 30 40 50 

In [ ]:
arr = np.array([50, 60, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 20, 30, 40])
size = 7
start = 12
cur_index = start
for i in range(size):
  print(arr[cur_index], end=" ")
  cur_index = (cur_index+1) % len(arr)


10 20 30 40 50 60 70 

In [ ]:
arr = np.array([50, 60, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 20, 30, 40])
start = 12
size = 7
last_index = (start+size-1)%len(arr)

for i in range(size):
  print(arr[last_index], end=" ")
  last_index -= 1

70 60 50 40 30 20 10 

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 0, 0, 0, 0, 0])
cir_arr = np.zeros(arr.shape, dtype="int")
start = 7
cur_index = start

for i in range(size):
  cir_arr[cur_index] = arr[i]
  cur_index = (cur_index+1)%len(arr)
print(cir_arr)

[50 60  0  0  0  0  0 10 20 30 40]


In [ ]:
arr = np.array([50, 60, 0, 0, 0, 0, 0, 10, 20, 30, 40])
new_arr = np.zeros(arr.shape, dtype="int")
start = 7
size = 6
cur_index = start

for i in range(size):
  new_arr[i] = arr[cur_index]
  cur_index = (cur_index+1)%len(arr)

print(new_arr)

[10 20 30 40 50 60  0  0  0  0  0]


In [ ]:
#multidimensional array
#iteration row-wise
def iteration(arr):
  row, col = arr.shape
  for i in range(row):
    for j in range(col):
      print(arr[i][j], end=" ")


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
iteration(arr)

1 2 3 4 5 6 7 8 9 

In [ ]:
#multidimensional array
#iteration col-wise
def iteration(arr):
  row, col = arr.shape
  for i in range(col):
    for j in range(row):
      print(arr[j][i], end=" ")


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
iteration(arr)

1 4 7 2 5 8 3 6 9 

In [ ]:
def shiftLeft(arr):
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0
  return arr

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(shiftLeft(arr))

[2 3 4 5 6 7 8 9 0]


In [ ]:
def reverse_in_place(arr):
  for i in range(len(arr)//2):
    temp = arr[i]
    arr[i] = arr[len(arr)-1-i]
    arr[len(arr)-1-i] = temp
  return arr


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(reverse_in_place(arr))

[9 8 7 6 5 4 3 2 1]


In [ ]:
def resize_array(oldarray, newCapacity):
  new_arr = np.zeros(len(oldarray)+newCapacity, dtype="int")
  for i in range(len(oldarray)):
    new_arr[i] = oldarray[i]
  return new_arr

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(resize_array(arr, 5))

[1 2 3 4 5 6 7 8 9 0 0 0 0 0]


In [ ]:
def insert(arr, size, element, index):
  if size==len(arr):
    new_arr = np.zeros(len(arr)+1, dtype="int")
    for i in range(len(arr)):
      new_arr[i] = arr[i]
    arr = new_arr

  for i in range(len(arr)-1, index, -1):
    arr[i] = arr[i-1]
  arr[index] = element
  return arr


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(insert(arr, 9, 10, 2))

[ 1  2 10  3  4  5  6  7  8  9]


In [ ]:
def remove(arr, size, index):
  for i in range(index+1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0
  return arr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(remove(arr, 9, 8))

[1 2 3 4 5 6 7 8 0]


In [ ]:
def bubbleSort(arr):
  for i in range(0, len(arr)):
    for j in range(1, len(arr)-i):
      if arr[j-1] > arr[j]:
        temp = arr[j-1]
        arr[j-1] = arr[j]
        arr[j] = temp
  return arr

arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(bubbleSort(arr))

[ 0  1  2  3  4  5  6  6  7  8  9 10]


In [ ]:
def selectionSort(arr):
  for i in range(0, len(arr)):
    min_index = i
    for j in range(i+1, len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    temp = arr[i]
    arr[i] = arr[min_index]
    arr[min_index] = temp
  return arr

arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(selectionSort(arr))

[ 0  1  2  3  4  5  6  6  7  8  9 10]


In [ ]:
def binarySearch(arr, value):
  arr = selectionSort(arr)
  lo = 0
  hi = len(arr)-1

  while lo<=hi:
    mid = (lo+hi)//2
    if arr[mid] == value:
      return f"{value} found at {mid}"
    elif arr[mid] > value:
      hi = mid-1
    elif arr[mid] < value:
      lo = mid+1
  return f"Value not found"

arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(binarySearch(arr, 3))

3 found at 3


In [ ]:
def reverse(arr):
  for i in range(0, len(arr)//2):
    temp = arr[i]
    arr[i] = arr[len(arr)-1-i]
    arr[len(arr)-1-i] = temp
  return arr

def diagonal(matrix):
  row, col = matrix.shape
  primary = np.zeros(row, dtype="int")
  secondary = np.zeros(col, dtype="int")

  for i in range(row):
    for j in range(col):
      primary[i] = matrix[i][i]
      secondary[i] = matrix[i][row-1-i]

  primary = reverse(primary)
  secondary = reverse(secondary)

  for i in range(row):
    for j in range(col):
      matrix[i][i] = primary[i]
      matrix[i][row-1-i] = secondary[i]

  return matrix

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(diagonal(arr))

[[16  2  3 13]
 [ 5 11 10  8]
 [ 9  7  6 12]
 [ 4 14 15  1]]


In [ ]:
def rotate(arr):
  temp = len(arr)//2+1
  new = np.zeros(temp, dtype="int")
  for i in range(0, len(arr), 2):
    new[i//2] = arr[i]
  temp1 = new[0]
  for i in range(1, len(new)):
    new[i-1] = new[i]
  new[len(new)-1] = temp1
  for i in range(0, len(arr), 2):
    arr[i] = new[i//2]

  return arr

arr = np.array([5, 2, 3, 7, 1, 4, 6])
print(rotate(arr))

[3 2 1 7 6 4 5]


In [ ]:
class Node:
  def __init__(self, value, next):
    self.value = value
    self.next = next

class linkedList:
  def __init__(self, arr):
    self.head = Node(arr[0], None)
    tail = self.head
    for i in range(1, len(arr)):
      n = Node(arr[i], None)
      tail.next = n
      tail = n

arr = np.array([1, 2, 3, 4, 5])
obj = linkedList(arr)

In [ ]:
class Node:
  def __init__(self, element, next):
    self.element = element
    self.next = next

class Stack:
  def __init__(self):
    self.top = None

  def push(self, elem):
    if self.top == None:
      n = Node(elem, None)
      self.top = n
    else:
      n = Node(elem, None)
      n.next = self.top
      self.top = n
  def pop(self):
    if self.top == None:
      return None
    else:
      n = self.top
      self.top = self.top.next
      n.next = None
      return n.element
  def peek(self):
    if self.top == None:
      return None
    else:
      return self.top.element
  def isEmpty(self):
    if self.top == None:
      return True
    else:
      return False

st = Stack()
st.push(4)
st.push(3)
st.push(5)
st.push(1)
st.push(9)


In [ ]:
def print_stack(st):
  if st.isEmpty():
    return None

  n = st.pop()
  print(n)
  print_stack(st)
  st.push(n)

st = Stack()
st.push(11)
st.push(3)
st.push(5)
st.push(1)
st.push(9)
print_stack(st)


9
1
5
3
11


In [ ]:
def reverse_string(st, string):
  for i in range(len(string)):
    st.push(string[i])
  while st.isEmpty() != True:
    n = st.pop()
    print(n, end="")

st = Stack()
string = "CSE220"
reverse_string(st, string)

022ESC

In [ ]:
def infix(st, arr):
  for i in range(len(arr)):
    if arr[i] == "+" or arr[i] == "-" or arr[i] == "*" or arr[i] == "/":
      if st.isEmpty() != True:
        x = int(st.pop())
        y = int(st.pop())
        if arr[i] == "+":
          st.push(y+x)
        elif arr[i] == "-":
          st.push(y-x)
        elif arr[i] == "*":
          st.push(y*x)
        elif arr[i] == "/":
          st.push(y/x)
    else:
      st.push(arr[i])
  return st.pop()

st = Stack()
arr = ["3", "2", "+", "4", "*", "5", "1", "-", "/"]
infix(st, arr)

5.0

In [ ]:
def shiftLeft(arr):
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0
  return arr

arr = np.array([1, 2, 3, 4, 5])
print(shiftLeft(arr))

[2 3 4 5 0]


In [ ]:
def rotateRightbyPlaces(arr, k):
  for i in range(k):
    temp = arr[len(arr)-1]
    for i in range(len(arr)-1, 0, -1):
      arr[i] = arr[i-1]
    arr[0] = temp
  return arr

arr = np.array([1, 2, 3, 4, 5])
print(rotateRightbyPlaces(arr, 3))

[3 4 5 1 2]


In [ ]:
def removeOccurance(arr, elem):
  count = 0
  while count < len(arr):
    if arr[count] == elem:
      for i in range(count+1, len(arr)):
        arr[i-1] = arr[i]
      arr[len(arr)-1] = 0
    else:
      count += 1
  return arr

arr = np.array([5, 3, 2, 5, 5, 6, 3, 5, 2, 1])
print(removeOccurance(arr, 3))

[5 2 5 5 6 5 2 1 0 0]


In [ ]:
def bubbleSort(arr):
  for i in range(0, len(arr)-1):
    for j in range(1, len(arr)-i):
      if arr[j] < arr[j-1]:
        temp = arr[j]
        arr[j] = arr[j-1]
        arr[j-1] = temp
  return arr

arr = np.array([3, 8, 0, 7, 1, 4, 6, 2, 9, 5, 10, 6])
print(bubbleSort(arr))

[ 0  1  2  3  4  5  6  6  7  8  9 10]


In [ ]:
def binarySearch(arr, elem):
  lo = 0
  hi = len(arr)-1
  while lo <= hi:
    mid = (lo + hi) // 2
    if arr[mid] == elem:
      return f"{elem} found at index: {mid}"
    elif arr[mid] > elem:
      hi = mid - 1
    elif arr[mid] < elem:
      lo = mid + 1

  return f"{elem} not found"

arr = np.array([2, 4, 6, 8, 9, 13, 15, 20])
print(binarySearch(arr, 8))

8 found at index: 3


In [ ]:
def reverse(arr):
  for i in range(0, len(arr)//2):
    temp = arr[i]
    arr[i] = arr[len(arr)-1-i]
    arr[len(arr)-1-i] = temp
  return arr
arr = np.array([1, 2, 3, 4, 5])
reverse(arr)
print(arr)

[5 4 3 2 1]


In [ ]:
def swapColumn(arr):
  row, col = arr.shape
  for i in range(row):
    for j in range(col//2):
      temp = arr[i][j]
      arr[i][j] = arr[i][len(arr)-1-j]
      arr[i][len(arr)-j-1] = temp
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(swapColumn(arr))

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
def secondary_diagonal(arr):
  row, col = arr.shape
  sum = 0
  for i in range(row):
    for j in range(col):
      if j==len(arr)-1-i:
        sum += arr[i][len(arr)-1-i]
  return sum

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(secondary_diagonal(arr))

34


In [ ]:
def row_downshift(arr):
  row, col = arr.shape
  temp_arr = np.zeros(col, dtype="int")
  for i in range(col):
    temp_arr[i] = arr[row-1][i]
  for i in range(row-1, -1, -1):
    for j in range(col):
      arr[i][j] = arr[i-1][j]
  for i in range(col):
    arr[0][i] = temp_arr[i]
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(row_downshift(arr))

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
def col_leftshift(arr):
  row, col = arr.shape
  temp = np.zeros(row, dtype="int")
  for i in range(row):
    temp[i] = arr[i][0]
  for i in range(1, col):
    for j in range(row):
      arr[j][i-1] = arr[j][i]
  for i in range(row):
    arr[i][col-1] = temp[i]
  return arr

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(col_leftshift(arr))

[[ 2  3  4  1]
 [ 6  7  8  5]
 [10 11 12  9]]


In [ ]:
def multiply_matrix(arr1, arr2):
  row1, col1 = arr1.shape
  row2, col2 = arr2.shape
  result = np.zeros(shape=(row1, col2), dtype="int")
  for i in range(row1):
    for j in range(col2):
      for k in range(col1):
        result += arr[i][k] * arr[k][j]
  return result

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(multiply_matrix(arr1, arr2))

[[1395 1395 1395]
 [1395 1395 1395]
 [1395 1395 1395]]


In [ ]:
def bubbleSort(arr):
  for i in range(0, len(arr)):
    for j in range(1, len(arr)-i):
      if ord(arr[j]) < ord(arr[j-1]):
        temp = arr[j]
        arr[j] = arr[j-1]
        arr[j-1] = temp
  return arr
arr = np.array(["N", "A", "H", "I", "N"])
print(bubbleSort(arr))

['A' 'H' 'I' 'N' 'N']


In [ ]:
class Node:
  def __init__(self, elem, next):
    self.elem = elem
    self.next = next
def linkedList(arr):
  head = Node(arr[0], None)
  temp = head
  for i in range(1, len(arr)):
    n = Node(arr[i], None)
    temp.next = n
    temp = n
  return head

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
head = linkedList(arr)

In [ ]:
def printNode(head):
  temp = head
  while temp != None:
    print(temp.elem, end=" ")
    temp = temp.next

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
head = linkedList(arr)
printNode(head)

1 2 3 4 5 6 7 8 9 10 

In [ ]:
def countNode(head):
  count = 0
  temp = head
  while temp != None:
    count += 1
    temp = temp.next
  return count


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
head = linkedList(arr)
print(countNode(head))

10


In [ ]:
def getNode(head, index):
  count = 0
  temp = head
  while temp != None:
    if count == index:
      return temp
    else:
      temp = temp.next
      count += 1

In [ ]:
def insert(head, elem, index):
  total_nodes = countNode(head)
  if index == 0:
    n = Node(elem, head)
    head = n
  elif 0<index<total_nodes:
    previous_node = getNode(head, index-1)
    next_node = getNode(head, index)
    n = Node(elem, next_node)
    previous_node.next = n
  elif index == total_nodes:
    previous_node = getNode(head, index-1)
    n = Node(elem, None)
    previous_node.next = n
  else:
    return f"Index out of bound"
  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
head = linkedList(arr)
head = insert(head, 90, 5)
printNode(head)

10 20 30 40 50 90 60 70 80 

In [ ]:
def remove(head, index):
  total_nodes = countNode(head)
  if index == 0:
    head = head.next
  elif 0<index<total_nodes-1:
    previous_node = getNode(head, index-1)
    next_node = getNode(head, index+1)
    previous_node.next = next_node
  elif index == total_nodes-1:
    previous_node = getNode(head, index-1)
    previous_node.next = None
  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
head = linkedList(arr)
head = remove(head, 7)
printNode(head)



10 20 30 40 50 60 70 

In [ ]:
#reverse-out of place
def reverse(head):
  new_head = Node(head.elem, None)
  temp = head.next
  while temp != None:
    n = Node(temp.elem, new_head)
    new_head = n
    temp = temp.next
  return new_head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
head = linkedList(arr)
head = reverse(head)
printNode(head)

80 70 60 50 40 30 20 10 

In [ ]:
#reverse(in-place)
def reverse(head):
  temp = head.next
  head.next = None
  while temp!=None:
    temp2 = temp.next
    temp.next = head
    head = temp
    temp = temp2
  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
head = linkedList(arr)
head = reverse(head)
printNode(head)

80 70 60 50 40 30 20 10 

In [ ]:
def leftRotate(head):
  total_nodes = countNode(head)
  last_node = getNode(head, total_nodes-1)
  temp = head
  head = head.next
  temp.next = None
  last_node.next = temp
  return head

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
head = linkedList(arr)
head = leftRotate(head)
printNode(head)

20 30 40 50 60 70 80 10 

In [ ]:
def removeDuplicate(head):
  sum = 0
  prev_node = head
  temp = head.next
  while temp != None:
    prev_elem = prev_node.elem
    if temp.elem == prev_elem:
      prev_node.next = temp.next
      sum += prev_elem
      temp = temp.next
    else:
      temp = temp.next
      prev_node = prev_node.next
  print(sum)
  return head

arr = np.array([1, 2, 5, 5, 9, 9])
head = linkedList(arr)
head = removeDuplicate(head)
printNode(head)

14
1 2 5 9 

In [ ]:
def pairwiseEqual(head1, head2):
  total_nodes = countNode(head1)
  count = 0
  isTrue = True
  while count<total_nodes:
    a = getNode(head1, count)
    a1 = a.elem
    b1 = a.next.elem
    c = getNode(head2, count)
    c1 = c.elem
    d1 = c.next.elem
    if a1 == c1 and b1 == d1 or a1 == d1 and b1 == c1:
      isTrue = True
    else:
      isTrue = False
    count += 2
  if isTrue:
    return True
  else:
    return False

arr1 = np.array([10, 15, 34, 42])
arr2 = np.array([15, 10, 34, 41])
head1 = linkedList(arr1)
head2 = linkedList(arr2)
print(pairwiseEqual(head1, head2))

False


In [ ]:
class Node:
  def __init__(self, elem, next, prev):
    self.elem = elem
    self.next = next
    self.prev = prev

def doublyLinkedList(arr):
  dh = Node(None, None, None)
  dh.next = dh
  dh.prev = dh
  tail = dh
  for i in range(len(arr)):
    n = Node(arr[i], dh, tail)
    tail.next = n
    tail = tail.next
    dh.prev = tail
  return dh

arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)

In [ ]:
def printNode(dh):
  temp = dh.next
  while temp != dh:
    print(temp.elem, end=" ")
    temp = temp.next

arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)
printNode(dh)

1 2 3 4 5 

In [ ]:
def countNode(dh):
  count = 0
  temp = dh.next
  while temp != dh:
    count += 1
    temp = temp.next
  return count

arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)
print(countNode(dh))

5


In [ ]:
def getNode(dh, index):
  count = 0
  temp = dh.next
  while temp != dh:
    if count == index:
      return temp
    temp = temp.next
    count += 1

arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)
x = getNode(dh, 2)
print(x.elem)

3


In [ ]:
def insert(dh, elem, index):
  next_node = getNode(dh, index)
  prev_node = next_node.prev
  n = Node(elem, next_node, prev_node)
  next_node.prev = n
  prev_node.next = n

arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)
insert(dh, 99, 4)
printNode(dh)

1 2 3 4 99 5 

In [ ]:
def remove(dh, index):
  removed_node = getNode(dh, index)
  prev_node = removed_node.prev
  next_node = removed_node.next
  prev_node.next = next_node
  next_node.prev = prev_node

arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)
remove(dh, 4)
printNode(dh)

1 2 3 4 

In [ ]:
#dummy headed doubly circular linked list reverse (in-place)
def reverse(dh):
  temp = dh.next
  dh.next = dh.prev
  dh.prev = temp
  while temp != dh:
    temp2 = temp.next
    temp.next = temp.prev
    temp.prev = temp2
    temp = temp2
  return dh

arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)
dh = reverse(dh)
printNode(dh)


5 4 3 2 1 

In [ ]:
def reverse(dh):
  temp = dh.next
  dh.next = dh.prev
  dh.prev = temp
  while temp != dh:
    temp2 = temp.next
    temp.next = temp.prev
    temp.prev = temp2
    temp = temp2
  return dh
arr = np.array([1, 2, 3, 4, 5])
dh = doublyLinkedList(arr)
dh = reverse(dh)
printNode(dh)

5 4 3 2 1 

In [ ]:
class Node:
  def __init__(self, elem, next):
    self.elem = elem
    self.next = next

def linkedList(arr):
  head = Node(arr[0], None)
  temp = head
  for i in range(1, len(arr)):
    n = Node(arr[i], None)
    temp.next = n
    temp = n
  return head

arr = np.array([1, 2, 3, 4, 5])
linkedList(arr)


In [ ]:
def getNode(head, index):
  temp = head
  count = 0
  while temp != None:
    if count == index:
      return temp
    else:
      count += 1
      temp = temp.next

In [ ]:
def printNode(head):
  temp = head
  while temp != None:
    print(temp.elem, end=" ")
    temp = temp.next

arr = np.array([1, 2, 3, 4, 5])
head = linkedList(arr)
printNode(head)

1 2 3 4 5 

In [ ]:
def countNode(head):
  temp = head
  count = 0
  while temp != None:
      count += 1
      temp = temp.next
  return count

In [ ]:
def insert(head, elem, index):
  total_nodes = countNode(head)
  if index==0:
    n = Node(elem, head)
    head = n
  elif 0<index<=total_nodes-1:
    prev_node = getNode(head, index-1)
    next_node = getNode(head, index)
    n = Node(elem, next_node)
    prev_node.next = n
  elif index==total_nodes:
    prev_node = getNode(head, index-1)
    n = Node(elem, None)
    prev_node.next = n
  return head

arr = np.array([1, 2, 3, 4, 5])
head = linkedList(arr)
head = insert(head, 999, 6)
printNode(head)

1 2 3 4 5 

In [ ]:
def remove(head, index):
  total_nodes = countNode(head)
  if index==0:
    head = head.next
  elif 0<index<total_nodes-1:
    prev_node = getNode(head, index-1)
    next_node = getNode(head, index+1)
    prev_node.next = next_node
  elif index==total_nodes-1:
    prev_node = getNode(head, index-1)
    prev_node.next = None
  return head

arr = np.array([1, 2, 3, 4, 5])
head = linkedList(arr)
head = remove(head, 3)
printNode(head)

1 2 3 5 

In [ ]:
def reverse(head):
  temp = head.next
  head.next = None
  while temp!=None:
    temp2 = temp.next
    temp.next = head
    head = temp
    temp = temp2
  return head

arr = np.array([1, 2, 3, 4, 5])
head = linkedList(arr)
head = reverse(head)
printNode(head)

5 4 3 2 1 

In [ ]:
class Node:
  def __init__(self, elem, next, prev):
    self.elem = elem
    self.next = next
    self.prev = prev
def linkedList(arr):
  dh = Node(None, None, None)
  dh.next = dh
  dh.prev = dh
  tail = dh
  for i in range(len(arr)):
    n = Node(arr[i], dh, tail)
    tail.next = n
    tail = n
    dh.prev = tail

  return dh

arr = np.array([1, 2, 3, 4, 5])
dh = linkedList(arr)


In [ ]:
def printNode(dh):
  temp = dh.next
  while temp != dh:
    print(temp.elem, end=" ")
    temp = temp.next

arr = np.array([1, 2, 3, 4, 5])
dh = linkedList(arr)
printNode(dh)

1 2 3 4 5 

In [ ]:
def getNode(dh, index):
  count = 0
  temp = dh.next
  while temp != dh:
    if index==count:
      return temp
    else:
      temp = temp.next
      count += 1

In [ ]:
def countNode(dh):
  count = 0
  temp = dh.next
  while temp != dh:
    count += 1
    temp = temp.next
  return count

In [ ]:
def insert(dh, elem, index):
  next_node = getNode(dh, index)
  prev_node = next_node.prev
  n = Node(elem, next_node, prev_node)
  prev_node.next = n
  next_node.prev = n
  return dh

arr = np.array([1, 2, 3, 4, 5])
dh = linkedList(arr)
insert(dh, 99, 4)
printNode(dh)


1 2 3 4 99 5 

In [ ]:
def remove(dh, index):
  removed_node = getNode(dh, index)
  prev_node = removed_node.prev
  next_node = removed_node.next
  prev_node.next = next_node
  next_node.prev = prev_node
  return dh

arr = np.array([1, 2, 3, 4, 5])
dh = linkedList(arr)
remove(dh, 2)
printNode(dh)

1 2 4 5 

In [ ]:
def reverse(dh):
  temp = dh.next
  dh.next = dh.prev
  dh.prev = temp
  while temp != dh:
    temp2 = temp.next
    temp.next = temp.prev
    temp.prev = temp2
    temp = temp2
  return dh

arr = np.array([0, 1, 2, 3, 4, 5])
dh = linkedList(arr)
dh = reverse(dh)
printNode(dh)

5 4 3 2 1 0 

In [ ]:
def factorial(n):
  if n==0 or n==1:
    return 1
  else:
    return n * factorial(n-1)

print(factorial(5))

120


In [ ]:
def fibonacci(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return fibonacci(n-1)+fibonacci(n-2)

print(fibonacci(10))

55


In [ ]:
class BTNode:
  def __init__(self, elem, left=None, right=None):
    self.elem = elem
    self.left = left
    self.right = right

In [ ]:
def isIdentical(root1, root2):
  if root1==None or root2 == None:
    if root1 == None and root2 == None:
      return True
    else:
      return False
  elif root1.elem == root2.elem:
    return isIdentical(root1.left, root2.left) and isIdentical(root1.right, root2.right)
  else:
    return False



root1 = BTNode(10)
root1.left = BTNode(5)
root1.right = BTNode(6)

root2 = BTNode(10)
root2.left = BTNode(5)



x = isIdentical(root1, root2)
print(x)

False


In [ ]:
def height(root):
  if root==None:
    return -1
  else:
    return 1+max(height(root.left), height(root.right))

def perfect(root, max_level=height(root)):
  if root == None:
    return True
  level = height


In [ ]:
def inorder(root):
  if root == None:
    return None
  inorder(root.left)
  print(root.elem, end=" ")
  inorder(root.right)

In [ ]:
def inorder_predecessor(root, value):
  if root == None:
    return None
  elif root.elem >=value:
    return inorder_predecessor(root.left, value)
  else:
    ans = inorder_predecessor(root.right, value)
    if ans != None:
      return ans
    else:
      return root.elem

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
inorder(root)
print()

x = inorder_predecessor(root, 99)
print(x)

20 40 50 60 70 75 80 85 90 95 99 
95


In [ ]:
def inorder_successor(root, value):
  if root==None:
    return None
  elif root.elem <= value:
    return inorder_successor(root.right, value)
  else:
    ans = inorder_successor(root.left, value)
    if ans != None:
      return ans
    else:
      return root.elem

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
inorder(root)
print()

x = inorder_successor(root, 75)
print(x)

20 40 50 60 70 75 80 85 90 95 99 
80


In [ ]:
def insert(root, value):
  if root == None:
    return None
  elif root.elem > value:
    if root.left == None:
      root.left = BTNode(value)
    else:
      return insert(root.left, value)
  elif root.elem < value:
    if root.right == None:
      root.right = BTNode(value)
    else:
      return insert(root.right, value)
  else:
    print("Duplicate!!")

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)

inorder(root)
print()

insert(root, 10)
inorder(root)
print()

insert(root, 30)
inorder(root)
print()

insert(root, 25)
inorder(root)
print()

20 40 50 60 70 75 80 85 90 95 99 
10 20 40 50 60 70 75 80 85 90 95 99 
10 20 30 40 50 60 70 75 80 85 90 95 99 
10 20 25 30 40 50 60 70 75 80 85 90 95 99 


In [ ]:
def delete(root, value):
  if root == None:
    return None
  if root.value > value:
    root.left = delete(root.left, value)
    return root
  elif root.value < value:
    root.right = delete(root.right, value)
    return root
  else:
    if root.left == None and root.right == None:
      return None
    elif root.left == None:
      return root.right
    elif root.right == None:
      return root.left
    else:
      predecessor = root.left
      while predecessor.right != None:
        predecessor = predecessor.right

    root.elem = predecessor.elem
    root.left = delete(root.left, predecessor.elem)
    return root

In [ ]:
def delete(root, value):
  if root == None:
    return None
  elif root.elem > value:
    root.left = delete(root.left, value)
    return root
  elif root.elem < value:
    root.right = delete(root.right, value)
    return root
  else:
    if root.left == None and root.right == None:
      return None
    elif root.left == None:
      return root.right
    elif root.right == None:
      return root.left
    else:
      pred = root.left
      while pred.right != None:
        pred = pred.right
    root.elem = pred.elem
    root.left = delete(root.left, pred.elem)
    return root

In [ ]:
class Node:
  def __init__(self, elem, next=None):
    self.elem = elem
    self.next = next

def has_duplicate(root, head=Node(None)):
  if root == None:
    return True
  temp = head
  while temp != None:
    if temp.elem == root.elem:
      print("Duplicate found:", root.elem)
      return False
    temp = temp.next
  temp = head
  while temp.next != None:
    temp = temp.next

  temp.next = Node(root.elem)
  is_here = has_duplicate(root.left, head)
  is_here = has_duplicate(root.right, head)
  if is_here:
    return "No Duplicate"
  else:
    return False


root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(85)
x = has_duplicate(root)
print(x)

Duplicate found: 70
Duplicate found: 85
False


In [ ]:
class MinHeap:
  def __init__(self, cap):
    self.arr = np.zeros(cap, dtype="int")
    self.size = 0
    self.cap = cap

  def insert(self, value):
    if self.size < self.cap:
      self.size += 1
      self.arr[self.size-1] = value
      self.swim(self.size-1)
    else:
      return

  def swim(self, index):
    if index>0:
      parent = (index-1)//2
      if self.arr[index] < self.arr[parent]:
        self.arr[index], self.arr[parent] = self.arr[parent], self.arr[index]
        self.swim(parent)
      else:
        return

  def extractMin(self):
    temp = self.arr[0]
    self.arr[0], self.arr[self.size-1] = self.arr[self.size-1], self.arr[0]
    self.size-=1
    self.arr[self.size] = 0
    self.sink(0)
    return temp

  def sink(self, index):
    if index<self.size:
      left = (2*index)+1
      right = (2*index)+2
      if left < self.size:
        if right < self.size:
          small = 0
          if self.arr[left] < self.arr[right]:
            small = left
          else:
            small = right
          if self.arr[small] < self.arr[index]:
            self.arr[small], self.arr[index] = self.arr[index], self.arr[small]
            self.sink(small)
        else:
          if self.arr[left] < self.arr[index]:
            self.arr[left], self.arr[index] = self.arr[index], self.arr[left]
            self.sink(left)

    return

  def heapSort(self, inp_arr):
    sort_heap = MinHeap(len(inp_arr))
    for i in range(len(inp_arr)):
      sort_heap.insert(inp_arr[i])
    for i in range(len(inp_arr)):
      extracted = sort_heap.extractMin()
      inp_arr[i] = extracted

    return inp_arr

  def getArray(self):
    return self.arr


In [ ]:
def cost_effective(arr):
  heap = MinHeap(len(arr))
  for i in range(len(arr)):
    heap.insert(arr[i])
  sum = 0
  while heap.size >= 2:
    extract1 = heap.extractMin()
    extract2 = heap.extractMin()
    sum += extract1+extract2
    heap.insert(extract1+extract2)

  return sum

arr = np.array([4, 3, 2, 6])
print(cost_effective(arr))

[4 6 5 0]
[6 9 0 0]
[15  0  0  0]
29


## Finals

In [ ]:
class MaxHeap:
  def __init__(self, cap):
    self.arr = np.zeros(cap, dtype="int")
    self.size = 0
    self.cap = cap

  def insert(self, value):
    if self.size < self.cap:
      self.size += 1
      self.arr[self.size-1] = value
      self.swim(self.size-1)
    else:
      return

  def swim(self, index):
    if index>0:
      parent = (index-1)//2
      if self.arr[index] > self.arr[parent]:
        self.arr[index], self.arr[parent] = self.arr[parent], self.arr[index]
        self.swim(parent)
      else:
        return

  def extractMax(self):
    temp = self.arr[0]
    self.arr[0], self.arr[self.size-1] = self.arr[self.size-1], self.arr[0]
    self.size-=1
    self.arr[self.size] = 0
    self.sink(0)
    return temp

  def sink(self, index):
    if index<self.size:
      left = (2*index)+1
      right = (2*index)+2
      if left < self.size:
        if right < self.size:
          big = 0
          if self.arr[left] > self.arr[right]:
            big = left
          else:
            big = right
          if self.arr[big] > self.arr[index]:
            self.arr[big], self.arr[index] = self.arr[index], self.arr[big]
            self.sink(big)
        else:
          if self.arr[left] > self.arr[index]:
            self.arr[left], self.arr[index] = self.arr[index], self.arr[left]
            self.sink(left)

    return

  def heapSort(self, inp_arr):
    sort_heap = MinHeap(len(inp_arr))
    for i in range(len(inp_arr)):
      sort_heap.insert(inp_arr[i])
    for i in range(len(inp_arr)):
      extracted = sort_heap.extractMin()
      inp_arr[i] = extracted

    return inp_arr

  def getArray(self):
    return self.arr


In [ ]:
class MinHeap:
  def __init__(self, cap):
    self.arr = np.zeros(cap, dtype="int")
    self.size = 0
    self.cap = cap

  def insert(self, value):
    if self.size < self.cap:
      self.size += 1
      self.arr[self.size-1] = value
      self.swim(self.size-1)
    else:
      return

  def swim(self, index):
    if index>0:
      parent = (index-1)//2
      if self.arr[index] < self.arr[parent]:
        self.arr[index], self.arr[parent] = self.arr[parent], self.arr[index]
        self.swim(parent)
      else:
        return

  def extractMin(self):
    temp = self.arr[0]
    self.arr[0], self.arr[self.size-1] = self.arr[self.size-1], self.arr[0]
    self.size-=1
    self.arr[self.size] = 0
    self.sink(0)
    return temp

  def sink(self, index):
    if index<self.size:
      left = (2*index)+1
      right = (2*index)+2
      if left < self.size:
        if right < self.size:
          small = 0
          if self.arr[left] < self.arr[right]:
            small = left
          else:
            small = right
          if self.arr[small] < self.arr[index]:
            self.arr[small], self.arr[index] = self.arr[index], self.arr[small]
            self.sink(small)
        else:
          if self.arr[left] < self.arr[index]:
            self.arr[left], self.arr[index] = self.arr[index], self.arr[left]
            self.sink(left)

    return

  def heapSort(self, inp_arr):
    sort_heap = MinHeap(len(inp_arr))
    for i in range(len(inp_arr)):
      sort_heap.insert(inp_arr[i])
    for i in range(len(inp_arr)):
      extracted = sort_heap.extractMin()
      inp_arr[i] = extracted

    return inp_arr

  def getArray(self):
    return self.arr


In [ ]:
def median(max_heap, min_heap, arr):
  for i in range(len(arr)):
    min_heap.insert(arr[i])
    if i%2!=0:
      max_heap.insert(min_heap.extractMin())

  if len(arr)%2!=0:
    value = min_heap.extractMin()
    print(value)
    min_heap.insert(value)
  else:
    value1 = min_heap.extractMin()
    value2 = max_heap.extractMax()
    print((value1+value2)/2)
    min_heap.insert(value1)
    max_heap.insert(value2)


arr = np.array([1, 6, 4, 3, 8, 7, 2])
max_heap = MaxHeap(len(arr))
min_heap = MinHeap(len(arr))
x = median(max_heap, min_heap, arr)
x

2


In [ ]:
class Node:
  def __init__(self, elem, next=None):
    self.elem = elem
    self.next = next

In [ ]:
#Stack class
class Stack:
  def __init__(self):
    self.top = None
  #Push operation
  def push(self, elem):
    if self.top == None:
      self.top = Node(elem, None)
    else:
      n = Node(elem, None)
      n.next = self.top
      self.top = n
  #Pop operation
  def pop(self):
    if self.top == None:
      return None
    else:
      n = self.top
      self.top = self.top.next
      n.next = None
      return n.elem
  #Peek operation
  def peek(self):
    if self.top == None:
      return None
    else:
      n = self.top.elem
      return n
  #isEmpty operation
  def isEmpty(self):
    if self.top == None:
      return True
    else:
      return False

In [ ]:
def print_stack(st):
  if st.isEmpty():
    return None
  else:
    n = st.pop()
    print(n)
    print_stack(st)
    st.push(n)

st = Stack()
for i in range(1, 10):
  st.push(i)
print_stack(st)

9
8
7
6
5
4
3
2
1


In [ ]:
def smaller(st, num):
  new_st = Stack()
  while True:
    x = st.pop()
    if x>=num:
      new_st.push(x)
    else:
      while new_st.isEmpty()!=True:
        st.push(new_st.pop())
      return x

st = Stack()
st.push(4)
st.push(1)
st.push(2)
st.push(3)






x = smaller(st, 3)
print("The smaller value is:", x)
print_stack(st)

The smaller value is: 2
3
1
4


In [ ]:
#Stack class
class Stack:
  def __init__(self):
    self.top = None
  #Push operation
  def push(self, elem):
    if self.top == None:
      x = (elem, elem)
      self.top = Node(x, None)
    else:
      cur_min = self.top.elem[1]
      if elem < cur_min:
        x = (elem, elem)
      else:
        x = (elem, cur_min)

      n = Node(x, None)
      n.next = self.top
      self.top = n
  #Pop operation
  def pop(self):
    if self.top == None:
      return None
    else:
      n = self.top
      self.top = self.top.next
      n.next = None
      return n.elem
  #Peek operation
  def peek(self):
    if self.top == None:
      return None
    else:
      n = self.top.elem
      return n
  #isEmpty operation
  def isEmpty(self):
    if self.top == None:
      return True
    else:
      return False

def getMin(st):
  x = st.pop()[1]
  return x

st = Stack()
st.push(2)
st.push(5)
st.push(7)
st.push(1)
st.push(3)
st.push(0)
x = getMin(st)
print(x)

0


In [ ]:
def fun(n):
  if n<2:
    return 3
  return fun(n-2)+2*fun(n-4)

print(fun(5))

15


In [ ]:
def hash_function(key):
  v = 0
  for i in key:
    if i.isdigit():
      v += int(i)
    else:
      v += ord(i)
  return v%3

x = hash_function("4G14")
print(x)

2


In [ ]:
class Node:
  def __init__(self, elem, next=None):
    self.elem = elem
    self.next = next

class HashTable:
  def __init__(self, size):
    self.ht = [None]*size


In [ ]:
class BTNode:
  def __init__(self, elem, left=None, right=None):
    self.elem = elem
    self.left = left
    self.right = right

def inorder(root):
  if root==None:
    return None
  inorder(root.left)
  print(root.elem, end=" ")
  inorder(root.right)

def postorder(root):
  if root==None:
    return None
  postorder(root.left)
  postorder(root.right)
  print(root.elem, end=" ")

In [ ]:
# construct tree from array
def tree_construction(arr, i=1):
  if i>=len(arr) or arr[i] == None:
    return None
  else:
    p = BTNode(arr[i])
    p.left = tree_construction(arr, 2*i)
    p.right = tree_construction(arr, 2*i+1)
    return p

root2 = tree_construction([None, 19, 22, 10, 32, 20, None, 30, None, 5, None, 7, None, None, 2,-2])
print("Postorder: ", end=" ")
postorder(root2)
print()


print("Inorder: ", end=" ")
inorder(root2)
print()

Postorder:  5 32 7 20 22 2 -2 30 10 19 
Inorder:  32 5 22 20 7 19 10 2 30 -2 


In [ ]:
def createBST(arr, l, r):
  if l > r:
    return None
  mid = (l+r)//2
  root = BTNode(arr[mid])

  root.left = createBST(arr, l, mid-1)
  root.right = createBST(arr, mid+1, r)
  return root


arr = np.array([5, 32, 7, 20, 22, 2, -2, 30, 10, 19])
root = createBST(arr, 0, len(arr)-1)
inorder(root)

In [ ]:
def insert(root, value):
  if root == None:
    return None
  elif root.elem > value:
    if root.left == None:
      root.left = BTNode(value)
    else:
      insert(root.left, value)
  elif root.elem < value:
    if root.right == None:
      root.right = BTNode(value)
    else:
      insert(root.right, value)
  else:
    print("Duplicate!!")

arr = np.array([32, 7, 20, 22, 2, -2, 30, 10, 19])
root = BTNode(5)
for i in range(len(arr)):
  insert(root, arr[i])

inorder(root)


-2 2 5 7 10 19 20 22 30 32 

In [ ]:
class Node:
  def __init__(self, elem, next=None):
    self.elem = elem
    self.next = next

def linkedList(arr):
  head = Node(arr[0])
  temp = head
  for i in range(1, len(arr)):
    n = Node(arr[i])
    temp.next = n
    temp = temp.next

  return head

def countNode(head):
  temp = head
  count = 0
  while temp!=None:
    count += 1
    temp = temp.next

  return count
def getNode(head, index):
  temp = head
  count = 0
  while temp != None:
    if count == index:
      return temp
    count += 1
    temp = temp.next

def printNode(head):
  temp = head
  while temp != None:
    print(temp.elem, end=" ")
    temp = temp.next

In [ ]:
def insert(head, value, index):
  total_nodes = countNode(head)
  if index == 0:
    n = Node(value, head)
    head = n
  elif 0 < index < total_nodes:
    next_node = getNode(head, index)
    n = Node(value, next_node)
    prev_node = getNode(head, index-1)
    prev_node.next = n
  elif index == total_nodes:
    prev_node = getNode(head, index-1)
    n = Node(value)
    prev_node.next = n

  return head


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
head = linkedList(arr)
head = insert(head, 100, 1)

printNode(head)

10 100 20 30 40 50 60 70 80 

In [ ]:
def reverse(head):
  temp = head.next
  head.next = None
  while temp != None:
    temp2 = temp.next
    temp.next = head
    head = temp
    temp = temp2
  return head


arr = np.array([1, 2, 3, 4, 5])
head = linkedList(arr)
head = reverse(head)
printNode(head)

5 4 3 2 1 

In [ ]:
def skewed(root):
  if root == None:
    return True

  if root.left != None and root.right != None:
    return False
  if (root.left != None):
    return skewed(root.left)
  elif (root.right != None):
    return skewed(root.right)


  return True


root = BTNode(10)
root.left = BTNode(5)
root.left.right = BTNode(6)
root.left.left = BTNode(8)
root.left.right.left = BTNode(3)
root.left.right.left.right = BTNode(7)
x = skewed(root)
print(x)

In [ ]:
class BTNode:
  def __init__(self, elem, left=None, right=None):
    self.elem = elem
    self.left = left
    self.right = right

def inorder(root):
  if root== None:
    return None
  inorder(root.left)
  print(root.elem, end=" ")
  inorder(root.right)

def insert(root, value):
  if root==None:
    return None
  elif root.elem > value:
    if root.left == None:
      root.left = BTNode(value)
    else:
      insert(root.left, value)
  elif root.elem < value:
    if root.right == None:
      root.right = BTNode(value)
    else:
      insert(root.right, value)
  else:
    print("Duplicate!")

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)

inorder(root)
print()

insert(root, 10)
inorder(root)
print()

insert(root, 30)
inorder(root)
print()

insert(root, 25)
inorder(root)
print()

20 40 50 60 70 75 80 85 90 95 99 
10 20 40 50 60 70 75 80 85 90 95 99 
10 20 30 40 50 60 70 75 80 85 90 95 99 
10 20 25 30 40 50 60 70 75 80 85 90 95 99 


In [ ]:
def predecessor(root, value):
  if root == None:
    return None
  elif root.elem >= value:
    return predecessor(root.left, value)
  else:
    ans = predecessor(root.right, value)
    if ans != None:
      return ans
    else:
      return root.elem

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
inorder(root)
print()

x = predecessor(root, 85)
print(x)

20 40 50 60 70 75 80 85 90 95 99 
80


In [ ]:
def successor(root, value):
  if root==None:
    return None

  elif root.elem <= value:
    return successor(root.right, value)
  else:
    ans = successor(root.left, value)
    if ans!=None:
      return ans
    else:
      return root.elem

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
inorder(root)
print()

x = successor(root, 90)
print(x)

20 40 50 60 70 75 80 85 90 95 99 
95


In [ ]:
# delete with the help predecessor
def delete(root, value):
  if root == None:
    return None

  elif root.elem > value:
    root.left = delete(root.left, value)
    return root
  elif root.elem < value:
    root.right = delete(root.right, value)
    return root
  else:
    if root.left==None and root.right == None:
      return None
    elif root.left == None:
      return root.right
    elif root.right == None:
      return root.left
    else:
      pred = root.left
      while pred.right != None:
        pred = pred.right
      root.elem = pred.elem
      root.left = delete(root.left, pred.elem)
      return root

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
inorder(root)
print()

delete(root, 90)
inorder(root)


20 40 50 60 70 75 80 85 90 95 99 
20 40 50 60 70 75 80 85 85 95 99 

In [ ]:
# delete with the help successor
def delete(root, value):
  if root == None:
    return None
  elif root.elem > value:
    root.left = delete(root.left, value)
    return root
  elif root.elem < value:
    root.right = delete(root.right, value)
    return root
  else:
    if root.left == None and root.right == None:
      return None
    elif root.left == None:
      return root.right
    elif root.right == None:
      return root.left
    successor = root.right
    while(successor.left != None):
      successor = successor.left

    root.elem = successor.elem
    root.right = delete(root.right, successor.elem)
    return root


root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
inorder(root)
print()

delete(root, 90)
inorder(root)


20 40 50 60 70 75 80 85 90 95 99 
20 40 50 60 70 75 80 85 95 99 

In [ ]:
def delete(root, value):
  if root == None:
    return None
  elif root.elem > value:
    root.left = delete(root.left, value)
    return root
  elif root.elem < value:
    root.right = delete(root.right, value)
    return root.right
  else:
    if root.left == None and root.right == None:
      return None
    elif root.left == None:
      return root.right
    elif root.right == None:
      return root.left
    else:
      pred = root.left
      while pred.right!=None:
        pred = pred.rihght
      root.elem = pred.elem
      root.left = delete(root.left, value)
      return root


root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
inorder(root)
print()

delete(root, 20)
inorder(root)

20 40 50 60 70 75 80 85 90 95 99 
40 50 60 70 75 80 85 90 95 99 

In [ ]:
class MinHeap:
  def __init__(self, cap):
    self.__arr = np.zeros(cap, dtype="int")
    self.__size = 0
    self.__cap = cap

  def insert(self, value):
    if self.__size < self.__cap:
      self.__size += 1
      self.__arr[self.__size-1] = value
      self.swim(self.__size-1)
    return

  def swim(self, index):
    if index > 0:
      parent = (index-1)//2
      if self.__arr[parent] > self.__arr[index]:
        self.__arr[parent], self.__arr[index] = self.__arr[index], self.__arr[parent]
        self.swim(parent)
      else:
        return

  def extractMin(self):
    temp = self.__arr[0]
    self.__arr[0], self.__arr[self.__size-1] = self.__arr[self.__size-1], self.__arr[0]
    self.__size -= 1
    self.__arr[self.size] = 0
    self.sink(0)
    return temp

  def sink(self, index):
    if index<self.__size:
      left = (2*index)+1
      right = (2*index)+2
      if left < self.__size:
        if right < self.__size:
          small = 0
          if self.__arr[left] < self.__arr[right]:
            small = left
          else:
            small = right
          if self.__arr[small] < self.__arr[index]:
            self.__arr[small], self.__arr[index] = self.__arr[index], self.__arr[small]
            self.sink(small)
        else:
          if  self.__arr[left] < self.__arr[index]:
            self.__arr[left], self.__arr[index] = self.__arr[index], self.__arr[left]
            self.sink(left)
    return

  def getArray(self):
    return self.__arr



In [ ]:
heap = MinHeap(10)
heap.insert(10)
heap.insert(120)
heap.insert(232)
heap.insert(250)
heap.insert(71)
heap.insert(155)
heap.insert(200)
heap.insert(170)
heap.insert(8)

print(f"The heap array is: {heap.getArray()}")
arr = np.array([10, 8, 9, 0, 6, 2, 1, 5, 4, 3, 7])
# print(f"The sorted array is: {heap.heapSort(arr)}")
# print(f"Extracted: {heap.extractMin()}")
# print(f"Extracted: {heap.extractMin()}")
# print(f"The heap array is: {heap.getArray()}")

The heap array is: [  8  10 155  71 120 232 200 250 170   0]


In [ ]:
class BTNode:
  def __init__(self, elem, left=None, right=None):
    self.elem = elem
    self.left = left
    self.right = right

def leftPrint(root):
  if root==None:
    return
  print(root.elem, end=" ")
  leftPrint(root.left)

def leafPrint(root):
  if root==None:
    return None
  elif root.left == None and root.right == None:
    print(root.elem, end=" ")
  leafPrint(root.left)
  leafPrint(root.right)
def rightPrint(root):
  if root == None:
    return None

  rightPrint(root.right)
  print(root.elem, end=" ")

def boundaryPrint(root):
  if root == None:
    return None
  leftPrint(root)
  leafPrint(root)
  rightPrint(root.right)

  return ""



root = BTNode(1)
root.left = BTNode(2)
root.right = BTNode(3)
root.left.left = BTNode(4)
root.left.right = BTNode(5)
root.right.left = BTNode(6)
root.right.right = BTNode(7)
x = boundaryPrint(root)
print(x)

1 2 4 4 5 6 7 7 3 


In [ ]:
def f(x):
  if x == 1:
    print(x, end=' ')
    return
  f(x // 2)
  print(x, end=' ')
f(16)

1 2 4 8 16 

In [35]:
class Node:
  def __init__(self, elem, next=None):
    self.elem = elem
    self.next = next

def linkedList(arr):
  head = Node(arr[0])
  temp = head
  for i in range(1, len(arr)):
    n = Node(arr[i])
    temp.next = n
    temp = temp.next

  return head

def countNode(head):
  temp = head
  count = 0
  while temp!=None:
    count += 1
    temp = temp.next

  return count
def getNode(head, index):
  temp = head
  count = 0
  while temp != None:
    if count == index:
      return temp
    count += 1
    temp = temp.next

def printNode(head):
  temp = head
  while temp != None:
    print(temp.elem, end=" --> ")
    temp = temp.next
  print("None")

arr = np.array(["A3", "A9", "A4", "A2", "A7", "A8", "A1"])
head = linkedList(arr)
printNode(head)

A3 --> A9 --> A4 --> A2 --> A7 --> A8 --> A1 --> None


In [ ]:
def rearrangeTokens(head, pos):
  temp = head
  for i in range(pos-2):
    temp = temp.next
  new_head = temp.next
  temp.next = None
  temp2 = new_head
  while temp2.next != None:
    temp2 = temp2.next

  while head != None:
    temp2.next = head
    temp2 = temp2.next
    head = head.next

  return new_head

arr = np.array(["A3", "A9", "A4", "A2", "A7", "A8", "A1"])
head = linkedList(arr)
head = rearrangeTokens(head, 4)
printNode(head)

A2 --> A7 --> A8 --> A1 --> A3 --> A9 --> A4 --> None


In [31]:
class BTNode:
  def __init__(self, elem, left=None, right=None):
    self.elem = elem
    self.left = left
    self.right = right
def is_here(root, key):
  if root.elem in key:
    return True
  else:
    return False
def is_valid(root, key):
  print(root.elem)
  if root == None:
    return None
  if root.left != None and root.right != None:
    if root.elem in key:
      x = is_here(root.left, key)
      y = is_here(root.right, key)
      if x:
        result = is_valid(root.left, key)
      else:
        result = is_valid(root.right, key)
  elif root.left == None and root.right == None:
    return True
  else:
    return False

  return result


root = BTNode("C")
root.left = BTNode("S")
root.right = BTNode("R")
root.left.left = BTNode("T")
root.left.right = BTNode("E")
root.right.left = BTNode("M")
root.right.right = BTNode("P")
root.right.right.left = BTNode("D")

x = is_valid(root, "CSE")
print(x)

C
S
E
True


In [34]:
def insert(root, value):
  if root == None:
    return None
  elif root.elem > value:
    if root.left == None:
      root.left = BTNode(value)
    else:
      insert(root.left, value)

  elif root.elem < value:
    if root.right == None:
      root.right = BTNode(value)
    else:
      insert(root.right, value)
  else:
    print("Duplicate!")

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)

inorder(root)
print()

insert(root, 10)
inorder(root)
print()

insert(root, 30)
inorder(root)
print()

insert(root, 25)
inorder(root)
print()

20 40 50 60 70 75 80 85 90 95 99 
10 20 40 50 60 70 75 80 85 90 95 99 
10 20 30 40 50 60 70 75 80 85 90 95 99 
10 20 25 30 40 50 60 70 75 80 85 90 95 99 


In [39]:
def height(root):
  if root==None:
    return -1
  else:
    return 1+max(height(root.left), height(root.right))

root = BTNode(70)
root.left = BTNode(50)
root.right = BTNode(90)
root.left.left = BTNode(40)
root.left.right = BTNode(60)
root.left.left.left = BTNode(20)
root.right.left = BTNode(80)
root.right.right = BTNode(95)
root.right.left.left = BTNode(75)
root.right.left.right = BTNode(85)
root.right.right.right = BTNode(99)
print(height(root))

3
