In [3]:
import numpy as np

In [2]:
class Node:
  def __init__(self, elem, weight=1, next=None):
    self.elem = elem
    self.weight = weight
    self.next = next


## Task 1

In [ ]:
class UndirectedGraph:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v):
    if self.adj[u] != None:
      temp = self.adj[u]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(v)
    else:
      self.adj[u] = Node(v)

    if self.adj[v] != None:
      temp = self.adj[v]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(u)
    else:
      self.adj[v] = Node(u)
  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

def maximum_degree(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    if graph.adj[i] != None:
      temp = graph.adj[i]
      num = 0
      while temp!=None:
        num += 1
        temp = temp.next

      if num >= max:
        max = num
        max_vertice = i

  return f"vertex with maximum degree is {max_vertice} and degree of that vertex is {max}"



G = UndirectedGraph(8)
G.addEdge(1, 2)
G.addEdge(1, 4)
G.addEdge(1, 5)
G.addEdge(1, 6)
G.addEdge(1, 7)
G.addEdge(2, 5)
G.addEdge(2, 6)
G.addEdge(2, 7)
G.addEdge(2, 3)
G.addEdge(3, 8)
G.addEdge(3, 5)
G.addEdge(3, 4)
G.addEdge(4, 5)
G.addEdge(5, 8)
G.addEdge(5, 6)
G.addEdge(6, 7)
G.addEdge(7, 8)
# G.show()
x = maximum_degree(G)
print(x)

vertex with maximum degree is 5 and degree of that vertex is 6


In [ ]:
class UndirectedMatrix:
  def __init__(self, n):
    self.num_of_vertex = n
    self.matrix = np.zeros(shape=(n, n), dtype="int")

  def addEdge(self, u, v):
    self.matrix[u-1][v-1] = 1
    self.matrix[v-1][u-1] = 1

  def show(self):
    print(self.matrix)

def maximum_degree(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    num = 0
    for j in range(graph.num_of_vertex):
      if graph.matrix[i][j] == 1:
        num += 1

    if num >= max:
      max = num
      max_vertice = i+1

  return f"vertex with maximum degree is {max_vertice} and degree of that vertex is {max}"

G = UndirectedMatrix(8)
G.addEdge(1, 2)
G.addEdge(1, 4)
G.addEdge(1, 5)
G.addEdge(1, 6)
G.addEdge(1, 7)
G.addEdge(2, 5)
G.addEdge(2, 6)
G.addEdge(2, 7)
G.addEdge(2, 3)
G.addEdge(3, 8)
G.addEdge(3, 5)
G.addEdge(3, 4)
G.addEdge(4, 5)
G.addEdge(5, 8)
G.addEdge(5, 6)
G.addEdge(6, 7)
G.addEdge(7, 8)

# G.show()
x = maximum_degree(G)
print(x)

vertex with maximum degree is 5 and degree of that vertex is 6


## Task 2

In [ ]:
class UndirectedWeightedGraph:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v, w):
    if self.adj[u] != None:
      temp = self.adj[u]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(v, w)
    else:
      self.adj[u] = Node(v, w)

    if self.adj[v] != None:
      temp = self.adj[v]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(u, w)
    else:
      self.adj[v] = Node(u, w)
  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

def sum_of_edge(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    if graph.adj[i] != None:
      temp = graph.adj[i]
      num = 0
      while temp != None:
        num += temp.weight
        temp = temp.next
      if num > max:
        max = num
        max_vertice = i

  return f"Vertex whose sum of edge weights is maximum is {max_vertice} and the value is {max}"


G = UndirectedWeightedGraph(7)
G.addEdge(1, 2, 2)
G.addEdge(1, 4, 3)
G.addEdge(1, 5, 2)
G.addEdge(1, 6, 3)
G.addEdge(2, 3, 3)
G.addEdge(2, 4, 4)
G.addEdge(2, 5, 1)
G.addEdge(2, 6, 4)
G.addEdge(3, 4, 1)
G.addEdge(3, 5, 3)
G.addEdge(3, 6, 2)
G.addEdge(3, 7, 4)
G.addEdge(4, 5, 5)
G.addEdge(4, 7, 2)
G.addEdge(5, 6, 4)
G.addEdge(5, 7, 3)
# G.show()
x = sum_of_edge(G)
print(x)

Vertex whose sum of edge weights is maximum is 5 and the value is 18


In [ ]:
class UndirectedWeightedMatrix:
  def __init__(self, n):
    self.num_of_vertex = n
    self.matrix = np.zeros(shape=(n, n), dtype="int")

  def addEdge(self, u, v, w):
    self.matrix[u-1][v-1] = w
    self.matrix[v-1][u-1] = w

  def show(self):
    print(self.matrix)

def sum_of_edge(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    num = 0
    for j in range(graph.num_of_vertex):
      num += graph.matrix[i][j]
    if num > max:
      max = num
      max_vertice = i+1

  return f"Vertex whose sum of edge weights is maximum is {max_vertice} and the value is {max}"


G = UndirectedWeightedMatrix(7)
G.addEdge(1, 2, 2)
G.addEdge(1, 4, 3)
G.addEdge(1, 5, 2)
G.addEdge(1, 6, 3)
G.addEdge(2, 3, 3)
G.addEdge(2, 4, 4)
G.addEdge(2, 5, 1)
G.addEdge(2, 6, 4)
G.addEdge(3, 4, 1)
G.addEdge(3, 5, 3)
G.addEdge(3, 6, 2)
G.addEdge(3, 7, 4)
G.addEdge(4, 5, 5)
G.addEdge(4, 7, 2)
G.addEdge(5, 6, 4)
G.addEdge(5, 7, 3)
G.show()

# x = sum_of_edge(G)
print(x)

[[0 2 0 3 2 3 0]
 [2 0 3 4 1 4 0]
 [0 3 0 1 3 2 4]
 [3 4 1 0 5 0 2]
 [2 1 3 5 0 4 3]
 [3 4 2 0 4 0 0]
 [0 0 4 2 3 0 0]]
Vertex whose sum of edge weights is maximum is 5 and the value is 18


## Task 3

In [ ]:
class DirectedWeightedGraph:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v, w):
    if self.adj[u] != None:
      temp = self.adj[u]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(v, w)
    else:
      self.adj[u] = Node(v, w)

  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

def maximum_degree(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    if graph.adj[i] != None:
      temp = graph.adj[i]
      num = 0
      while temp!=None:
        num += 1
        temp = temp.next

      if num >= max:
        max = num
        max_vertice = i

  return f"vertex with maximum degree is {max_vertice} and degree of that vertex is {max}"

G = DirectedWeightedGraph(8)
G.addEdge(1, 2, 2)
G.addEdge(1, 8, 2)
G.addEdge(2, 3, 2)
G.addEdge(3, 6, 3)
G.addEdge(4, 3, 2)
G.addEdge(4, 8, 3)
G.addEdge(4, 5, 3)
G.addEdge(5, 6, 1)
G.addEdge(6, 2, 6)
G.addEdge(6, 1, 4)
G.addEdge(6, 7, 7)
G.addEdge(7, 3, 4)
G.addEdge(7, 4, 2)
G.addEdge(8, 7, 2)
G.addEdge(8, 5, 1)
G.addEdge(5, 1, 2)
G.addEdge(6, 8, 2)
# G.show()

x = maximum_degree(G)
print(x)

vertex with maximum degree is 6 and degree of that vertex is 4


In [ ]:
class DirectedWeightedMatrix:
  def __init__(self, n):
    self.num_of_vertex = n
    self.matrix = np.zeros(shape=(n, n), dtype="int")

  def addEdge(self, u, v, w):
    self.matrix[u-1][v-1] = w

  def show(self):
    print(self.matrix)

def maximum_degree(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    num = 0
    for j in range(graph.num_of_vertex):
      if graph.matrix[i][j] != 0:
        num += 1

    if num >= max:
      max = num
      max_vertice = i+1

  return f"vertex with maximum degree is {max_vertice} and degree of that vertex is {max}"


G = DirectedWeightedMatrix(8)
G.addEdge(1, 2, 2)
G.addEdge(1, 8, 2)
G.addEdge(2, 3, 2)
G.addEdge(3, 6, 3)
G.addEdge(4, 3, 2)
G.addEdge(4, 8, 3)
G.addEdge(4, 5, 3)
G.addEdge(5, 6, 1)
G.addEdge(6, 2, 6)
G.addEdge(6, 1, 4)
G.addEdge(6, 7, 7)
G.addEdge(7, 3, 4)
G.addEdge(7, 4, 2)
G.addEdge(8, 7, 2)
G.addEdge(8, 5, 1)
G.addEdge(5, 1, 2)
G.addEdge(6, 8, 2)
# G.show()

x = maximum_degree(G)
print(x)

vertex with maximum degree is 6 and degree of that vertex is 4


In [ ]:
class DirectedWeightedGraph:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v, w):
    if self.adj[u] != None:
      temp = self.adj[u]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(v, w)
    else:
      self.adj[u] = Node(v, w)

  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

def sum_of_edge(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    if graph.adj[i] != None:
      temp = graph.adj[i]
      num = 0
      while temp != None:
        num += temp.weight
        temp = temp.next
      if num > max:
        max = num
        max_vertice = i

  return f"Vertex whose sum of edge weights is maximum is {max_vertice} and the value is {max}"


G = DirectedWeightedGraph(8)
G.addEdge(1, 2, 2)
G.addEdge(1, 8, 2)
G.addEdge(2, 3, 2)
G.addEdge(3, 6, 3)
G.addEdge(4, 3, 2)
G.addEdge(4, 8, 3)
G.addEdge(4, 5, 3)
G.addEdge(5, 6, 1)
G.addEdge(6, 2, 6)
G.addEdge(6, 1, 4)
G.addEdge(6, 7, 7)
G.addEdge(7, 3, 4)
G.addEdge(7, 4, 2)
G.addEdge(8, 7, 2)
G.addEdge(8, 5, 1)
G.addEdge(5, 1, 2)
G.addEdge(6, 8, 2)
# G.show()
x = sum_of_edge(G)
print(x)

Vertex whose sum of edge weights is maximum is 6 and the value is 19


In [ ]:
class DirectedWeightedMatrix:
  def __init__(self, n):
    self.num_of_vertex = n
    self.matrix = np.zeros(shape=(n, n), dtype="int")

  def addEdge(self, u, v, w):
    self.matrix[u-1][v-1] = w

  def show(self):
    print(self.matrix)

def sum_of_edge(graph):
  max = 0
  max_vertice = 0
  for i in range(graph.num_of_vertex):
    num = 0
    for j in range(graph.num_of_vertex):
      num += graph.matrix[i][j]
    if num > max:
      max = num
      max_vertice = i+1

  return f"Vertex whose sum of edge weights is maximum is {max_vertice} and the value is {max}"


G = DirectedWeightedMatrix(8)
G.addEdge(1, 2, 2)
G.addEdge(1, 8, 2)
G.addEdge(2, 3, 2)
G.addEdge(3, 6, 3)
G.addEdge(4, 3, 2)
G.addEdge(4, 8, 3)
G.addEdge(4, 5, 3)
G.addEdge(5, 6, 1)
G.addEdge(6, 2, 6)
G.addEdge(6, 1, 4)
G.addEdge(6, 7, 7)
G.addEdge(7, 3, 4)
G.addEdge(7, 4, 2)
G.addEdge(8, 7, 2)
G.addEdge(8, 5, 1)
G.addEdge(5, 1, 2)
G.addEdge(6, 8, 2)
# G.show()
x = sum_of_edge(G)
print(x)

Vertex whose sum of edge weights is maximum is 6 and the value is 19


## Task 4

In [15]:
class DirectedWeightedGraph:
  def __init__(self, n):
    self.num_of_vertex = n+1
    self.adj = np.empty(self.num_of_vertex, dtype=Node)

  def addEdge(self, u, v, w):
    if self.adj[u] != None:
      temp = self.adj[u]
      while temp.next != None:
        temp = temp.next
      temp.next = Node(v, w)
    else:
      self.adj[u] = Node(v, w)

  def show(self):
    for i in range(1, self.num_of_vertex):
      print(i, end=": ")
      temp = self.adj[i]
      while (temp != None):
        print(temp.elem, end=" --> ")
        temp = temp.next
      print("None")

def convertToUndirected(graph):
  for i in range(1, graph.num_of_vertex):
    if graph.adj[i] != None:
      head = graph.adj[i]
      while head != None:
        temp = graph.adj[head.elem]
        exist = False
        while temp != None:
          if temp.elem == i:
            exist = True
            break
          temp = temp.next

        if exist != True:
          if graph.adj[head.elem] != None:
            temp2 = graph.adj[head.elem]
            while temp2.next != None:
              temp2 = temp2.next
            temp2.next = Node(i, head.weight)
          else:
            graph.adj[head.elem] = Node(i, head.weight)
        head = head.next

G = DirectedWeightedGraph(6)
G.addEdge(1, 2, 2)
G.addEdge(1, 3, 3)
G.addEdge(2, 6, 2)
G.addEdge(2, 5, 3)
G.addEdge(3, 6, 2)
G.addEdge(4, 5, 1)
G.addEdge(4, 2, 1)
G.addEdge(5, 6, 3)
G.addEdge(6, 1, 6)
G.show()

x = convertToUndirected(G)

G.show()

1: 2 --> 3 --> None
2: 6 --> 5 --> None
3: 6 --> None
4: 5 --> 2 --> None
5: 6 --> None
6: 1 --> None
1: 2 --> 3 --> 6 --> None
2: 6 --> 5 --> 1 --> 4 --> None
3: 6 --> 1 --> None
4: 5 --> 2 --> None
5: 6 --> 2 --> 4 --> None
6: 1 --> 2 --> 3 --> 5 --> None
